### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by wzrdx** [wzrdx/pumpichu#5]

**Comment by 0xViva** [comment]
I suggest intergrating tailwind css for ease with work on responsiveness:

https://tailwindcss.com/docs/responsive-design

Can also suggest adding triggers of toasts upon user interactions:

https://flowbite.com/docs/components/toast/

**Comment by wzrdx** [comment]
> I suggest intergrating tailwind css for ease with work on responsiveness:
> 
> https://tailwindcss.com/docs/responsive-design
> 
> Can also suggest adding triggers of toasts upon user interactions:
> 
> https://flowbite.com/docs/components/toast/

We already have Chakra UI integrated which has both responsiveness and toasts functionality

**Comment by 0xViva** [comment]
#

> > I suggest intergrating tailwind css for ease with work on responsiveness:
> > https://tailwindcss.com/docs/responsive-design
> > Can also suggest adding triggers of toasts upon user interactions:
> > https://flowbite.com/docs/components/toast/
> 
> We already have Chakra UI integrated which has both responsiveness and toasts functionality

Awesome, all things covered then. :)
